import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Skeleton from "./components/Skeleton";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { userStoreMiddleware } from "./lib/session";
import UserProvider from "@/app/lib/UserProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  userStoreMiddleware();
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider />
        <Skeleton>{children}</Skeleton>
        <ToastContainer />
      </body>
    </html>
  );
}
